### ISSUE TITLE
request: re-add nats

### ISSUE THREAD

**Issue by vyp** [archhaskell/habs#183]
Continuing from #179 and 5de5bcb, when I try to update, I still get:

    error: failed to prepare transaction (could not satisfy dependencies)
    :: haskell-nats: requires ghc=7.8.4-1
    :: haskell-nats: requires haskell-hashable=1.2.3.1-2

`haskell-nats` seems to be a dependency for `haskell-pandoc-citeproc` and `haskell-pandoc`, though not directly (though I also might be wrong about this?). So removing it fails too. Have I done something wrong?

I know you said nats didn't make it over to ghc 7.10.1, but is this relevant?:
https://github.com/ekmett/nats/blob/9eb53dc5974ea93d14a29da892d95fd773cd38b4/nats.cabal#L44-45

And for the `requires haskell-hashable=1.2.3.1-2` line: https://github.com/ekmett/nats/blob/9eb53dc5974ea93d14a29da892d95fd773cd38b4/nats.cabal#L51 (because the current version of hashable in the repository is `1.2.3.2-76`).

**Comment by magthe** [comment]
As you point out, `nats` lives in `base` now, so there's no need for the package to be re-added.  There are a few packages out there that depend on `nats` and don't bother to make the dependency dependant on the Ghc version.  For these packages it would be interesting to add an empty `nat` package.  Unfortunately building the docs fail if there are no modules in the library.  Given the low number of packages depending on `nats` (2) I've opted to patch their Cabal files, rather than make the necessary patches to build an empty `haskell-nats` package.  See <https://github.com/archhaskell/habs/blob/master/patches/semigroups.cabal>.and <https://github.com/archhaskell/habs/blob/master/patches/th-orphans.cabal>.

So just remove the old `haskell-nats` package and then re-install `haskell-pandoc`.

**Comment by vyp** [comment]
Awesome! Much thanks! :sparkles: :+1:

As I said before, I couldn't remove nats since it was a dependency to another package, so I just simply removed and then reinstalled the entire haskell platform (including pandoc obviously), and everything worked. (I didn't want to do this first without asking since pandoc is a high priority package for me.)

Also, forgot to say thanks for bringing over pandoc-citeproc too in #179, so Kudos. :)
