### ISSUE TITLE
Can't install haskell-ghc-mod and haskell-stack-tool

### ISSUE THREAD

**Issue by tuxayo** [archhaskell/habs#220]
When I uninstall all haskell-* package.
And I install haskell-stack-tool
And I try to install haskell-ghc-mod
Then I get:
```
error: failed to commit transaction (conflicting files)
haskell-src-exts: /usr/share/doc/ghc/html/libraries/haskell-src-exts exists in filesystem
Errors occurred, no packages were upgraded.
```

When I try to install both in the same transaction
Then I get:
```
error: failed to commit transaction (conflicting files)
/usr/share/doc/ghc/html/libraries/haskell-src-exts exists in both 'haskell-src-exts' and 'haskell-haskell-src-exts'
Errors occurred, no packages were upgraded.
```

**Comment by magthe** [comment]
It looks like you end up mixing packages from `[haskell-core]` (`haskell-haskell-src-exts`) and `[community]`, which isn't a very good thing to do.

`ghc-mod` is not in `[haskell-core]` anymore; since it's been so slow with adopting new ghc versions in the past I decided to simply skip it this time. Feel free to raise a ticket if you feel strongly that it should be otherwise.
