### ISSUE TITLE
request: ghc-mod

### ISSUE THREAD

**Issue by tuxayo** [archhaskell/habs#222]
Followup of https://github.com/archhaskell/habs/issues/220#issuecomment-243708413
My use case if it can help estimated the importance of this package if for haskell integration by the editors spacemacs/emacs and atom.

**Comment by tuxayo** [comment]
I abandoned the haskell-core repo to get it from the community repo. That's fine for me so if no one else asks for it, it might not wroth the effort.

**Comment by magthe** [comment]
In the past `ghc-mode` has been a pain to have in the repo due to the upstream developers being *very* slow with adapting to new versions of Ghc. That means every time I've brought in a new version of Ghc I've decided to (temporarily) drop `ghc-mod`. With the move to Ghc8 it was the same, except that now there now are options to `ghc-mode`.

* `hsdev`, supported in Sublime and there is an Atom plugin (WIP) as well - it's in `haskell-core`
* `intero`, supported in Spacemacs (at least on the development branch) - it's used via `stack`, which is in `haskell-core`

I know that the `ghc-mod` upstream was a lot quicker with Ghc8 support this time, but I've not bothered with bringing it in yet anyway.
