### ISSUE TITLE
Question: How often is arch haskell updated?

### ISSUE THREAD

**Issue by lvicentesanchez** [archhaskell/habs#228]
I'm using Arch Haskell as the main source for haskell packages and I would like to know how often is updated. Stack is on version 1.4.0 but the latest stable one is 1.5.1.

**Comment by magthe** [comment]
It's basically updated when I have time to update :)

I'm in the middle of a move to the latest Ghc, and the last time I tried adding _stack_ it was prevented by a dependency on some other lib that _pandoc_ (or some other already added tool) also has a dependency, but the required versions had a non-empty intersection. It's been a few days since I had a look at it though, so that might have been fixed by now.
